apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.14.3
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest