apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName | quote }}
      port: {{ .Values.service.ports.mongodb }}
      targetPort: mongodb
  selector: 
    app.kubernetes.io/component: mongodb