apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmcluster
  namespace: argocd
spec:
  project: default
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  source:
    path: kustomize/vmCluster
    repoURL: https://github.com/yunzck8s/cloudNative.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m