apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator
  namespace: argocd
spec:
  project: default
  source:
    path: charts/victoria-metrics-operator
    repoURL: https://github.com/yunzck8s/cloudNative.git
    targetRevision: main
    helm:
      releaseName: victoria-metrics-operator
      valueFiles:
        - ../values/vm.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m