{{- if .Values.persistence.enabled  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default_custom
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "syncplant-front.name" . }}
spec:
  storageClassName: {{ .Values.persistence.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
---
{{- if .Values.persistence.enabled  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: B3dm
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "syncplant-front.name" . }}
spec:
  storageClassName: {{ .Values.persistence.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}