apiVersion: v1
appVersion: RELEASE.2021-08-25T00-41-18Z
description: Multi-Cloud Object Storage
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: minio
sources:
- https://github.com/minio/minio
version: 2.0.0
